<a href="https://colab.research.google.com/github/CodeHunterOfficial/ABC_DataMining/blob/main/ML/3_Feature_Engineering_%D0%A1%D0%BD%D0%B8%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80%D0%BD%D0%BE%D1%81%D1%82%D0%B8_(Dimension_Reduction).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3. Feature Engineering. Снижение размерности (Dimension Reduction)
### Оглавление

### 1. **Снижение размерности (Dimension Reduction)**  
#### 1.1 **Неконтролируемые методы (Unsupervised Methods)**  
   - 1.1.1 Метод главных компонент (PCA, Principal Components Analysis)  
   - 1.1.2 Ядерный метод главных компонент (Kernel PCA, Kernel Principal Components Analysis)  
   - 1.1.3 t-SNE (t-Distributed Stochastic Neighbor Embedding)  
   - 1.1.4 UMAP (Uniform Manifold Approximation and Projection)  
   - 1.1.5 Метод независимых компонент (ICA, Independent Component Analysis)  
   - 1.1.6 Неотрицательная матричная факторизация (NMF, Non-Negative Matrix Factorization)  
   - 1.1.7 Автоэнкодеры (Autoencoders, Neural Network-Based Dimensionality Reduction)  
   - 1.1.8 Изометрическое отображение (Isomap, Isometric Mapping)  
   - 1.1.9 Локально линейное вложение (LLE, Locally Linear Embedding)  
   - 1.1.10 Собственные отображения Лапласа (Laplacian Eigenmaps)  

#### 1.2 **Контролируемые методы (Supervised Methods)**  
   - 1.2.1 Линейный дискриминантный анализ (LDA, Linear Discriminant Analysis)  
   - 1.2.2 Квадратичный дискриминантный анализ (QDA, Quadratic Discriminant Analysis)  
   - 1.2.3 Метод частичных наименьших квадратов (PLS, Partial Least Squares)  
   - 1.2.4 Обобщенный дискриминантный анализ (GDA, Generalized Discriminant Analysis)  
   - 1.2.5 Канонический корреляционный анализ (CCA, Canonical Correlation Analysis)  
   - 1.2.6 Контролируемый метод главных компонент (Supervised PCA, Supervised Principal Components Analysis)  
   - 1.2.7 Дискриминантный анализ Фишера (FDA, Fisher Discriminant Analysis)  


### 1. **Снижение размерности (Dimension Reduction)**  

Снижение размерности (Dimension Reduction) — это процесс уменьшения количества признаков (фичей) в наборе данных, при этом сохраняя как можно больше полезной информации. Это важный этап в feature engineering, который помогает улучшить производительность моделей машинного обучения, сократить время обучения, уменьшить риск переобучения и упростить интерпретацию данных.

#### Зачем нужно снижение размерности?

1. **Устранение избыточности данных**: Многие признаки могут быть коррелированы между собой, что приводит к избыточности информации. Снижение размерности помогает устранить эту проблему.
2. **Ускорение обучения моделей**: Меньшее количество признаков означает меньше вычислений, что ускоряет процесс обучения.
3. **Уменьшение переобучения**: Модели, обученные на данных с меньшим количеством признаков, менее склонны к переобучению, особенно если исходный набор данных был очень большим.
4. **Визуализация данных**: Снижение размерности до 2 или 3 измерений позволяет визуализировать данные, что помогает лучше понять их структуру.


### 1.1 Неконтролируемые методы (Unsupervised Methods)

Неконтролируемые методы снижения размерности — это подходы, которые не используют информацию о целевой переменной (если она есть). Они работают исключительно на основе структуры данных, пытаясь сохранить важные закономерности или отношения между объектами. Эти методы особенно полезны, когда у нас нет размеченных данных или когда мы хотим исследовать структуру данных без явного целевого признака.


### Метод главных компонент (PCA, Principal Components Analysis)

Метод главных компонент (PCA) — это метод снижения размерности данных, который позволяет выделить наиболее важные направления (компоненты) в данных и спроецировать данные на эти направления. PCA широко используется для визуализации данных, сжатия информации и удаления шума.

#### Основные шаги PCA:

1. **Стандартизация данных**  
   Если признаки имеют разные масштабы, их необходимо стандартизировать, чтобы каждый признак вносил равный вклад в анализ.  
   Формула стандартизации:  
$$
   z_{ij} = \frac{x_{ij} - \mu_j}{\sigma_j}
$$  
   где:  
   - $x_{ij}$ — значение $i$-го объекта по $j$-му признаку,  
   - $\mu_j$ — среднее значение $j$-го признака,  
   - $\sigma_j$ — стандартное отклонение $j$-го признака.

2. **Вычисление ковариационной матрицы**  
   Ковариационная матрица показывает, как признаки коррелируют друг с другом.  
   Формула ковариационной матрицы $\Sigma$:  
$$
   \Sigma = \frac{1}{n-1} Z^T Z
$$  
   где:  
   - $Z$ — матрица стандартизированных данных,  
   - $n$ — количество объектов.

3. **Вычисление собственных значений и собственных векторов**  
   Собственные значения ($\lambda$) и собственные векторы ($v$) ковариационной матрицы находятся из уравнения:  
$$
   \Sigma v = \lambda v
$$  
   Собственные векторы определяют направления главных компонент, а собственные значения — их важность (дисперсию).

4. **Сортировка собственных значений и векторов**  
   Собственные значения сортируются в порядке убывания. Соответствующие собственные векторы также переупорядочиваются. Первые $k$ собственных векторов соответствуют $k$ главным компонентам.

5. **Проецирование данных на главные компоненты**  
   Данные проецируются на выбранные главные компоненты для снижения размерности.  
   Формула проекции:  
$$
   Y = Z W
$$  
   где:  
   - $Y$ — матрица данных в новом пространстве,  
   - $W$ — матрица, содержащая $k$ собственных векторов.

#### Пример алгоритма PCA:

1. Стандартизируем данные:  
$$
   Z = \begin{bmatrix}
   z_{11} & z_{12} & \dots & z_{1p} \\
   z_{21} & z_{22} & \dots & z_{2p} \\
   \vdots & \vdots & \ddots & \vdots \\
   z_{n1} & z_{n2} & \dots & z_{np}
   \end{bmatrix}
$$

2. Вычисляем ковариационную матрицу:  
$$
   \Sigma = \frac{1}{n-1} Z^T Z
$$

3. Находим собственные значения и векторы:  
$$
   \Sigma v = \lambda v
$$

4. Сортируем собственные значения и векторы:  
$$
   \lambda_1 \geq \lambda_2 \geq \dots \geq \lambda_p
$$

5. Выбираем $k$ главных компонент и проецируем данные:  
$$
   Y = Z W_k
$$  
   где $W_k$ — матрица из $k$ собственных векторов.

#### Интерпретация результатов:

- **Главные компоненты**: Новые оси, вдоль которых данные имеют наибольшую дисперсию.  
- **Доля объясненной дисперсии**: Доля дисперсии, объясняемая каждой компонентой:  
$$
   \text{Доля} = \frac{\lambda_i}{\sum_{j=1}^p \lambda_j}
$$  
- **Снижение размерности**: Выбор $k$ компонент, которые объясняют большую часть дисперсии.

#### Преимущества PCA:
- Уменьшает размерность данных.  
- Удаляет корреляции между признаками.  
- Упрощает визуализацию данных.

#### Недостатки PCA:
- Линейность: PCA предполагает линейные зависимости между признаками.  
- Интерпретируемость: Главные компоненты могут быть трудны для интерпретации.  
- Потеря информации: При сильном снижении размерности часть информации может быть потеряна.



Рассмотрим конкретный числовой пример применения метода главных компонент (PCA) для снижения размерности данных.

### Исходные данные
Пусть у нас есть следующие данные с двумя признаками $X_1$ и $X_2$:

$$
X = \begin{bmatrix}
1 & 2 \\
2 & 3 \\
3 & 4 \\
4 & 5
\end{bmatrix}
$$

Здесь 4 объекта и 2 признака.



### Шаг 1: Стандартизация данных
Сначала стандартизируем данные, чтобы каждый признак имел среднее значение 0 и стандартное отклонение 1.

Средние значения признаков:
$$
\mu_1 = \frac{1 + 2 + 3 + 4}{4} = 2.5, \quad \mu_2 = \frac{2 + 3 + 4 + 5}{4} = 3.5
$$

Стандартные отклонения признаков:
$$
\sigma_1 = \sqrt{\frac{(1-2.5)^2 + (2-2.5)^2 + (3-2.5)^2 + (4-2.5)^2}{4}} = 1.118, \quad \sigma_2 = 1.118
$$

Стандартизированные данные:
$$
Z = \begin{bmatrix}
\frac{1-2.5}{1.118} & \frac{2-3.5}{1.118} \\
\frac{2-2.5}{1.118} & \frac{3-3.5}{1.118} \\
\frac{3-2.5}{1.118} & \frac{4-3.5}{1.118} \\
\frac{4-2.5}{1.118} & \frac{5-3.5}{1.118}
\end{bmatrix} = \begin{bmatrix}
-1.342 & -1.342 \\
-0.447 & -0.447 \\
0.447 & 0.447 \\
1.342 & 1.342
\end{bmatrix}
$$



### Шаг 2: Вычисление ковариационной матрицы
Ковариационная матрица $\Sigma$ вычисляется по формуле:
$$
\Sigma = \frac{1}{n-1} Z^T Z
$$

Подставляем данные:
$$
\Sigma = \frac{1}{3} \begin{bmatrix}
-1.342 & -0.447 & 0.447 & 1.342 \\
-1.342 & -0.447 & 0.447 & 1.342
\end{bmatrix} \begin{bmatrix}
-1.342 & -1.342 \\
-0.447 & -0.447 \\
0.447 & 0.447 \\
1.342 & 1.342
\end{bmatrix}
$$

Вычисляем:
$$
\Sigma = \frac{1}{3} \begin{bmatrix}
4 & 4 \\
4 & 4
\end{bmatrix} = \begin{bmatrix}
1.333 & 1.333 \\
1.333 & 1.333
\end{bmatrix}
$$



### Шаг 3: Вычисление собственных значений и собственных векторов
Решаем уравнение $\Sigma v = \lambda v$.

Характеристическое уравнение:
$$
\text{det}(\Sigma - \lambda I) = 0
$$

Подставляем:
$$
\text{det}\left(\begin{bmatrix}
1.333 - \lambda & 1.333 \\
1.333 & 1.333 - \lambda
\end{bmatrix}\right) = 0
$$

Раскрываем определитель:
$$
(1.333 - \lambda)^2 - (1.333)^2 = 0
$$

Решаем:
$$
\lambda^2 - 2.666\lambda = 0 \implies \lambda(\lambda - 2.666) = 0
$$

Собственные значения:
$$
\lambda_1 = 2.666, \quad \lambda_2 = 0
$$

Собственные векторы:
Для $\lambda_1 = 2.666$:
$$
\begin{bmatrix}
1.333 - 2.666 & 1.333 \\
1.333 & 1.333 - 2.666
\end{bmatrix} \begin{bmatrix}
v_{11} \\
v_{12}
\end{bmatrix} = 0
$$
$$
\begin{bmatrix}
-1.333 & 1.333 \\
1.333 & -1.333
\end{bmatrix} \begin{bmatrix}
v_{11} \\
v_{12}
\end{bmatrix} = 0
$$
Решаем систему:
$$
-1.333 v_{11} + 1.333 v_{12} = 0 \implies v_{11} = v_{12}
$$
Нормируем:
$$
v_1 = \begin{bmatrix}
\frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}}
\end{bmatrix} = \begin{bmatrix}
0.707 \\
0.707
\end{bmatrix}
$$

Для $\lambda_2 = 0$:
$$
\begin{bmatrix}
1.333 & 1.333 \\
1.333 & 1.333
\end{bmatrix} \begin{bmatrix}
v_{21} \\
v_{22}
\end{bmatrix} = 0
$$
Решаем систему:
$$
1.333 v_{21} + 1.333 v_{22} = 0 \implies v_{21} = -v_{22}
$$
Нормируем:
$$
v_2 = \begin{bmatrix}
\frac{1}{\sqrt{2}} \\
-\frac{1}{\sqrt{2}}
\end{bmatrix} = \begin{bmatrix}
0.707 \\
-0.707
\end{bmatrix}
$$



### Шаг 4: Сортировка собственных значений и векторов
Собственные значения уже отсортированы: $\lambda_1 = 2.666$, $\lambda_2 = 0$.  
Соответствующие собственные векторы: $v_1 = \begin{bmatrix} 0.707 \\ 0.707 \end{bmatrix}$, $v_2 = \begin{bmatrix} 0.707 \\ -0.707 \end{bmatrix}$.



### Шаг 5: Проецирование данных на главные компоненты
Выберем первую главную компоненту (с наибольшим собственным значением) и спроецируем данные на неё.

Матрица проекции:
$$
W = \begin{bmatrix}
0.707 \\
0.707
\end{bmatrix}
$$

Проекция данных:
$$
Y = Z W = \begin{bmatrix}
-1.342 & -1.342 \\
-0.447 & -0.447 \\
0.447 & 0.447 \\
1.342 & 1.342
\end{bmatrix} \begin{bmatrix}
0.707 \\
0.707
\end{bmatrix} = \begin{bmatrix}
-1.342 \cdot 0.707 + (-1.342) \cdot 0.707 \\
-0.447 \cdot 0.707 + (-0.447) \cdot 0.707 \\
0.447 \cdot 0.707 + 0.447 \cdot 0.707 \\
1.342 \cdot 0.707 + 1.342 \cdot 0.707
\end{bmatrix} = \begin{bmatrix}
-1.897 \\
-0.632 \\
0.632 \\
1.897
\end{bmatrix}
$$



### Итог
Данные были спроецированы на первую главную компоненту, и их размерность снижена с 2 до 1.  
Результат проекции:
$$
Y = \begin{bmatrix}
-1.897 \\
-0.632 \\
0.632 \\
1.897
\end{bmatrix}
$$

Этот пример иллюстрирует, как PCA может быть использован для снижения размерности данных.


Реализуем метод главных компонент (PCA) на Python для приведенного числового примера. Мы будем использовать библиотеку `numpy` для выполнения всех вычислений.

### Код Python:


In [1]:
import numpy as np

# Исходные данные
X = np.array([[1, 2],
              [2, 3],
              [3, 4],
              [4, 5]])

# Шаг 1: Стандартизация данных
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
Z = (X - mean) / std

print("Стандартизированные данные:\n", Z)

# Шаг 2: Вычисление ковариационной матрицы
cov_matrix = np.cov(Z, rowvar=False)

print("Ковариационная матрица:\n", cov_matrix)

# Шаг 3: Вычисление собственных значений и собственных векторов
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Собственные значения:\n", eigenvalues)
print("Собственные векторы:\n", eigenvectors)

# Шаг 4: Сортировка собственных значений и векторов
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

print("Отсортированные собственные значения:\n", eigenvalues)
print("Отсортированные собственные векторы:\n", eigenvectors)

# Шаг 5: Проецирование данных на главные компоненты
# Выберем первую главную компоненту (с наибольшим собственным значением)
k = 1
W = eigenvectors[:, :k]

Y = Z.dot(W)

print("Проекция данных на главные компоненты:\n", Y)

Стандартизированные данные:
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
Ковариационная матрица:
 [[1.33333333 1.33333333]
 [1.33333333 1.33333333]]
Собственные значения:
 [2.66666667 0.        ]
Собственные векторы:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Отсортированные собственные значения:
 [2.66666667 0.        ]
Отсортированные собственные векторы:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Проекция данных на главные компоненты:
 [[-1.8973666 ]
 [-0.63245553]
 [ 0.63245553]
 [ 1.8973666 ]]




### Проверка с использованием `sklearn`:
Для проверки воспользуемся библиотекой `sklearn`, которая предоставляет встроенную реализацию PCA.



In [2]:
from sklearn.decomposition import PCA

# Применение PCA
pca = PCA(n_components=1)
Y_sklearn = pca.fit_transform(Z)

print("Проекция данных (sklearn):\n", Y_sklearn)

Проекция данных (sklearn):
 [[-1.8973666 ]
 [-0.63245553]
 [ 0.63245553]
 [ 1.8973666 ]]




Результаты совпадают, что подтверждает правильность нашей реализации.