<a href="https://colab.research.google.com/github/CodeHunterOfficial/A_PythonLibraries/blob/main/NV/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Библиотека NumPy

## Введение

NumPy (Numerical Python) — это одна из основных библиотек для научных вычислений в Python. Она предоставляет мощные инструменты для работы с многомерными массивами и матрицами, а также содержит множество математических функций для выполнения операций над этими данными. Благодаря своей эффективности и простоте использования, NumPy стал стандартом в области численных вычислений и анализа данных.

### Основные характеристики NumPy

1. **Многомерные массивы**: NumPy предоставляет объект `ndarray`, который представляет собой многомерный массив. Это позволяет легко хранить и манипулировать большими объемами данных.
2. **Эффективные операции**: NumPy позволяет выполнять операции над массивами без необходимости писать сложные циклы, что делает код более читаемым и производительным.
3. **Векторизация**: Векторизация позволяет использовать встроенные операции над массивами, что значительно ускоряет вычисления по сравнению с обычными циклами Python.
4. **Удобные функции**: NumPy предлагает множество функций для выполнения математических, статистических и линейных алгебраических операций.

## Установка

Чтобы установить NumPy, используйте команду pip в терминале или командной строке. Это позволит вам загрузить и установить библиотеку для использования в вашем проекте.

In [ ]:
pip install numpy

## Основные объекты NumPy

### Массивы `ndarray`

Объект `ndarray` (n-dimensional array) является основным элементом NumPy. Он позволяет создавать массивы любой размерности, что делает его очень удобным для хранения и обработки данных.

#### Создание массивов

NumPy предоставляет различные способы создания массивов. Рассмотрим несколько основных методов:

1. **Создание одномерного массива**

Начнем с простого примера создания одномерного массива, который состоит из целых чисел.

In [ ]:
import numpy as np

# Создание одномерного массива с использованием функции np.array()
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


2. **Создание двумерного массива**

Теперь создадим двумерный массив. Это может быть полезно для представления данных в виде таблицы.

In [ ]:
# Создание двумерного массива с двумя строками и тремя столбцами
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


3. **Создание многомерного массива**

Мы можем создавать массивы и с более высокой размерностью. Рассмотрим пример трехмерного массива.

In [ ]:
# Создание трехмерного массива
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Свойства массивов

Массивы в NumPy имеют несколько важных свойств, которые могут помочь нам понять их структуру:

- **shape**: форма массива, которая показывает его размерность и количество элементов в каждом измерении.
- **dtype**: тип данных элементов массива, что позволяет управлять памятью и производительностью.

Рассмотрим, как получить эти свойства для двумерного массива:

In [ ]:
print(arr_2d.shape)
print(arr_2d.dtype)

(2, 3)
int64


### Инициализация массивов

NumPy также предлагает функции для инициализации массивов с заранее заданными значениями, такими как нули или единицы.

1. **Создание массива нулей**

Вы можете создать массив, заполненный нулями, с помощью функции `np.zeros()`. Это может быть полезно, например, для инициализации весов в нейронной сети.

In [ ]:
# Создание двумерного массива 2x3, заполненного нулями
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


2. **Создание массива единиц**

Аналогично, можно создать массив, заполненный единицами, с помощью функции `np.ones()`.

In [ ]:
# Создание двумерного массива 2x3, заполненного единицами
ones_array = np.ones((2, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


3. **Создание массива с произвольными значениями**

Для создания массива с случайными числами можно использовать `np.random.rand()`. Это удобно для генерации данных для тестирования.

In [ ]:
# Создание двумерного массива 2x3 с случайными числами от 0 до 1
random_array = np.random.rand(2, 3)
print(random_array)

[[0.28653874 0.29406347 0.60933009]
 [0.50093641 0.44379262 0.34598268]]


## Основные операции с массивами

Теперь давайте рассмотрим, как можно выполнять различные операции с массивами. NumPy предоставляет удобные и эффективные способы работы с данными.

### Индексация и срезы

Индексация и срезы позволяют извлекать отдельные элементы или подмассивы из массивов. Это полезно, когда нужно работать только с определенными частями данных.

1. **Индексация**

Индексация в NumPy позволяет получить доступ к конкретным элементам массива, используя индексы. Она начинается с нуля, как и в большинстве языков программирования. Индексы задаются в квадратных скобках, где первым идет индекс строки, а затем — индекс столбца (если массив многомерный). Это позволяет извлекать отдельные элементы или целые подмножества массива.

В NumPy можно обращаться как к элементам одномерных массивов, так и многомерных. Например, для одномерного массива `arr_1d` обращение к элементу по индексу выглядит как `arr_1d[i]`, где `i` — порядковый номер элемента. Для двумерных массивов можно использовать формат `arr_2d[i, j]`, где `i` — индекс строки, а `j` — индекс столбца.

Пример индексации в двумерном массиве:

In [ ]:
import numpy as np

# Создаем двумерный массив 3x3
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Получение элемента из первой строки и второго столбца
print(arr_2d[0, 1])

2


2. **Булева индексация**

Булева индексация — это метод выборки элементов массива, который позволяет извлекать данные на основе логических условий. В этом методе создается булев массив (массив из значений `True` и `False`), который затем используется для фильтрации исходного массива. Элементы, соответствующие условию (`True`), остаются в результате, а остальные отбрасываются.

Булеву индексацию можно использовать для выполнения операций фильтрации, маскирования данных или выделения подмассивов по критериям.

Пример использования булевой индексации:

In [ ]:
import numpy as np

# Создаем двумерный массив 3x3
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Получаем булев массив, где элементы больше 3
bool_index = arr_2d > 3

# Выводим булев массив
print(bool_index)


# Получение элементов массива, которые больше 3
filtered_elements = arr_2d[bool_index]
print(filtered_elements)

[[False False False]
 [ True  True  True]
 [ True  True  True]]
[4 5 6 7 8 9]


В данном примере создается булев массив того же размера, что и исходный, где каждый элемент равен `True`, если соответствующий элемент исходного массива удовлетворяет условию (больше 3). Затем с помощью этого булевого массива производится выборка элементов, которые больше 3.

Булева индексация особенно полезна для работы с большими массивами, где необходимо выполнять массовые операции фильтрации, например, удаление или изменение элементов, соответствующих определенным условиям.



В NumPy существует несколько способов индексации массивов помимо обычной и булевой. Они помогают эффективно работать с массивами различной размерности. Вот основные типы индексации:

### 1. **Обычная индексация** (Прямой доступ по индексу)
Это базовая форма индексации, где для одномерного массива передается один индекс, а для многомерного — несколько индексов (один на каждую ось).

Пример:

In [ ]:
import numpy as np

arr_1d = np.array([10, 20, 30])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Получение элемента из одномерного массива
print(arr_1d[1])

# Получение элемента из двумерного массива
print(arr_2d[2, 1])

20
8


### 2. **Индексация массивом индексов** (Fancy indexing)

Этот тип индексации позволяет извлекать элементы массива с помощью списков или массивов индексов. Это даёт возможность выбирать элементы в произвольном порядке, в отличие от срезов, которые возвращают непрерывные подмножества.

Пример:

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 10, 10, 60, 20, 10, 20, 40, 50, 10])
x={}

for i in arr:
  if i in x:
    x[i]+=1
  else:
    x[i]=1

print(x)

{10: 5, 20: 3, 30: 1, 40: 2, 50: 2, 60: 1}


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Индексация массивом индексов
index_array = [0, 2, 4]
print(arr[index_array])  # Output: [10 30 50]

[10 30 50]


Для многомерных массивов можно также указывать массивы индексов для каждой оси:


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Получение элементов по произвольным индексам
row_indices = [0, 1, 2]
col_indices = [2, 1, 0]
print(arr_2d[row_indices, col_indices])

[3 5 7]


### 3. **Индексация через `np.ix_`**

Когда нужно получить подмножество массива с помощью нескольких массивов индексов по каждой оси, можно использовать функцию `np.ix_`. Это создаёт сетку индексов, что позволяет выбирать элементы из массива на пересечении индексов.

Пример:


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Индексация с использованием np.ix_
rows = np.array([0, 2])
cols = np.array([1, 2])

sub_array = arr_2d[np.ix_(rows, cols)]
print(sub_array)

[[2 3]
 [8 9]]


### 4. **Индексация с помощью `...` (ellipsis)**

Оператор `...` в NumPy позволяет сокращать запись индексов, особенно в массивах высокой размерности. Он заменяет недостающие оси. Это особенно полезно, когда известно, что индексация по некоторым осям пропускается.

Пример:

In [ ]:
arr_3d = np.arange(27).reshape(3, 3, 3)

# Полная форма
print(arr_3d[1, :, 2])

# Использование ellipsis для сокращения записи
print(arr_3d[1, ..., 2])


[11 14 17]
[11 14 17]


### 5. **Индексация по нескольким осям с `np.newaxis`**

С помощью `np.newaxis` можно расширить размерность массива, добавляя новые оси. Это полезно при изменении формы массива для выполнения математических операций (например, для выравнивания размеров массивов при выполнении операций).

Пример:


In [ ]:
arr = np.array([1, 2, 3])

# Добавление новой оси
arr_2d = arr[:, np.newaxis]
print(arr_2d)

[[1]
 [2]
 [3]]


### 6. **Комбинированная индексация**

Разные типы индексации можно комбинировать в одном выражении. Например, можно использовать булеву индексацию вместе с массивом индексов или срезами.

Пример:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Комбинирование булевой индексации и индекса массива
bool_index = arr > 20
indices = [2, 3, 4]

print(arr[bool_index])

[30 40 50]


3. **Срезы**

Срезы позволяют извлекать подмассивы или части массива, что делает их важным инструментом для работы с данными. В NumPy срезы работают так же, как и срезы списков в Python, но предоставляют более гибкие возможности для работы с многомерными массивами. Давайте разберём это подробнее.

#### Основной синтаксис срезов

Основной синтаксис для создания среза массива выглядит следующим образом:

```python
array[start:stop:step]
```

- `start`: начальный индекс среза (включительно).
- `stop`: конечный индекс среза (не включительно).
- `step`: шаг, определяющий, через сколько элементов нужно брать элементы массива.

По умолчанию:
- Если `start` не указан, срез начинается с 0.
- Если `stop` не указан, срез продолжается до конца массива.
- Если `step` не указан, по умолчанию он равен 1.

#### Примеры срезов на одномерных массивах

1. **Извлечение части массива**

Для одномерного массива срезы работают так же, как и для списка.

In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Извлечение элементов с 2-го по 5-й (индексы 2, 3, 4)
print(arr[2:5])

[2 3 4]


2. **Срез с указанием шага**

Вы можете извлекать элементы с шагом через несколько элементов.


In [ ]:
# Извлечение каждого второго элемента
print(arr[::2])

[0 2 4 6 8]


3. **Срез с отрицательным шагом**

Отрицательный шаг позволяет делать срез в обратном порядке.


In [ ]:
# Обратный срез: все элементы в обратном порядке
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


4. **Извлечение элементов с начала или до конца**

Если не указать `start` или `stop`, срез будет идти до начала или конца массива.


In [ ]:
# Все элементы до 5-го индекса
print(arr[:5])

# Все элементы с 5-го индекса до конца
print(arr[5:])

[0 1 2 3 4]
[5 6 7 8 9]



#### Срезы на многомерных массивах

Для многомерных массивов (например, двумерных или трёхмерных) срезы позволяют извлекать подмассивы, указав срез для каждой оси. Рассмотрим двумерные массивы.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

1. **Срезы по строкам и столбцам**

Для двумерного массива нужно указать срезы для каждой оси (строк и столбцов).


In [ ]:
# Извлечение первой и второй строки
print(arr_2d[0:2, :])

[[1 2 3]
 [4 5 6]]


Здесь `0:2` означает, что мы берём строки с индексами 0 и 1 (первые две строки), а `:` указывает на то, что берутся все столбцы.

2. **Извлечение подмассива**

Можно комбинировать срезы по строкам и столбцам для извлечения подмассива.


In [ ]:
# Извлечение подмассива, состоящего из элементов с первой по вторую строку и второго по третий столбец
print(arr_2d[0:2, 1:3])

[[2 3]
 [5 6]]


Здесь `0:2` означает выбор строк с индексами 0 и 1, а `1:3` — столбцы с индексами 1 и 2.

3. **Срезы по одной оси**

Вы можете извлечь все элементы одной строки или столбца, указав срезы только по одной оси.

In [ ]:
# Извлечение второй строки
print(arr_2d[1, :])

# Извлечение третьего столбца
print(arr_2d[:, 2])

[4 5 6]
[3 6 9]


4. **Извлечение элементов с шагом**

Шаг в срезах можно также применять в многомерных массивах.

In [ ]:
# Извлечение каждого второго элемента в столбцах и строках
print(arr_2d[::2, ::2])

[[1 3]
 [7 9]]


Здесь `::2` означает, что берутся каждая вторая строка и каждый второй столбец.

#### Пример использования отрицательных индексов

Отрицательные индексы позволяют указывать элементы с конца массива.

In [ ]:
# Извлечение последнего элемента массива
print(arr_2d[-1, -1])

9


Также можно использовать отрицательные индексы для срезов:

In [ ]:
# Срез последних двух строк
print(arr_2d[-2:, :])

[[4 5 6]
 [7 8 9]]


#### Примеры сложных срезов

Комбинирование срезов даёт возможность извлекать сложные подмассивы.

1. **Извлечение диагонали**

Хотя NumPy имеет встроенную функцию для извлечения диагонали (`np.diagonal()`), срезы могут быть использованы для этой же цели:

In [ ]:
# Извлечение диагональных элементов (1, 5, 9)
print(arr_2d[range(3), range(3)])

[1 5 9]


2. **Перестановка с шагом**

Вы можете комбинировать шаг и срезы для извлечения элементов с определённой регулярностью.

In [ ]:
# Извлечение элементов с первого и третьего столбцов через одну строку
print(arr_2d[::2, [0, 2]])

[[1 3]
 [7 9]]


### Математические операции

NumPy позволяет выполнять математические операции над массивами поэлементно, что значительно упрощает код и делает его более читаемым. Вот некоторые из основных операций:

1. **Сложение и вычитание**

NumPy поддерживает поэлементное сложение и вычитание массивов. Если массивы имеют одинаковую форму, то их можно складывать или вычитать друг из друга напрямую, без использования циклов.

In [ ]:
import numpy as np

# Создание двух массивов
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Сложение массивов
print(arr_a + arr_b)

# Вычитание массивов
print(arr_a - arr_b)

[5 7 9]
[-3 -3 -3]


2. **Умножение и деление**

NumPy позволяет легко выполнять поэлементное умножение и деление между массивами. Эти операции также требуют, чтобы массивы имели одинаковую форму.

In [ ]:
# Поэлементное умножение
print(arr_a * arr_b)

# Поэлементное деление
print(arr_a / arr_b)

[ 4 10 18]
[0.25 0.4  0.5 ]


Обратите внимание, что операции выполняются поэлементно, то есть каждая операция выполняется между соответствующими элементами массивов.

3. **Универсальные функции (ufuncs)**

NumPy предоставляет широкий спектр универсальных функций (universal functions), которые могут быть применены ко всему массиву сразу, без необходимости итераций. Это включает функции для вычисления корня, экспоненты, логарифмов, тригонометрических операций и других математических операций.

Примеры использования некоторых из этих функций:

In [ ]:
# Корень квадратный
print(np.sqrt(arr_a))

# Экспонента (e^x)
print(np.exp(arr_a))

# Синус
print(np.sin(arr_a))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


4. **Агрегатные операции**

NumPy также поддерживает агрегатные функции для выполнения математических операций на всем массиве, такие как нахождение суммы, минимального или максимального значения.

In [ ]:
# Сумма всех элементов массива
print(np.sum(arr_a))

# Минимальное значение
print(np.min(arr_a))

# Максимальное значение
print(np.max(arr_a))

6
1
3


### Статистические функции

NumPy предлагает обширные возможности для выполнения статистического анализа данных. Это полезно для обработки больших массивов данных и быстрой их обработки.

In [ ]:
data = np.array([1, 2, 3, 4, 5])

# Среднее значение
print(np.mean(data))

# Медиана
print(np.median(data))

# Стандартное отклонение
print(np.std(data))

# Дисперсия
print(np.var(data))

# Максимум и минимум
print(np.max(data))
print(np.min(data))

3.0
3.0
1.4142135623730951
2.0
5
1


Эти функции предоставляют быстрый доступ к основным статистическим характеристикам массива, что полезно при анализе данных.


### Операции над массивами

NumPy предлагает ряд инструментов для манипуляции массивами. Это включает операции, такие как транспонирование, изменение формы массива, объединение и разделение массивов.

1. **Транспонирование**

Транспонирование меняет местами строки и столбцы массива. Оно особенно полезно для работы с матрицами, например, в линейной алгебре или машинном обучении.

In [ ]:
# Создание двумерного массива
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Транспонирование массива
print(arr_2d.T)

[[1 4]
 [2 5]
 [3 6]]


2. **Изменение формы массива**

NumPy позволяет легко изменять форму массива с помощью функции `reshape`. Это может быть полезно, если нужно преобразовать одномерный массив в многомерный и наоборот.

In [ ]:
# Изменение формы массива (1x6 -> 2x3)
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


3. **Объединение массивов**

Объединение массивов в NumPy осуществляется с помощью функции `np.concatenate()`, которая позволяет объединять массивы по различным осям (строкам или столбцам).


In [ ]:
# Создание двух массивов
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Объединение массивов по строкам (axis=0)
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

[[1 2]
 [3 4]
 [5 6]]



4. **Разделение массивов**

Функция `np.split()` позволяет разделить массив на несколько частей, что удобно, например, при подготовке данных.



In [ ]:
# Разделение массива на две части
split_arr = np.split(arr1, 2)
print(split_arr)

[array([[1, 2]]), array([[3, 4]])]


### Бродкастинг


Бродкастинг — это способ, которым NumPy расширяет формы (размерности) меньших массивов до размеров больших массивов, чтобы можно было производить операции с массивами разного размера. Эта техника позволяет избежать неэффективных циклов, которые могли бы значительно замедлить выполнение программы.

#### Пример без бродкастинга

Рассмотрим пример, когда массивы имеют одинаковую форму и операция между ними выполняется "элемент за элементом":


In [ ]:
import numpy as np

# Два одинаковых массива
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Элемент-wise сложение
result = a + b
print(result)

[5 7 9]




В этом примере каждый элемент массива `a` складывается с соответствующим элементом массива `b`. Так как оба массива имеют одинаковую форму, никаких дополнительных действий не требуется.

#### Пример с бродкастингом

Теперь рассмотрим пример, когда один из массивов имеет меньшую форму:


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10])

# Сложение с бродкастингом
result = a + b
print(result)

[11 12 13]


В этом примере массив `b` содержит только один элемент. NumPy автоматически "расширяет" его до формы массива `a`, так что операция выполняется как будто бы `b` имел вид `[10, 10, 10]`. Эта операция и есть суть бродкастинга.

### 2. Правила бродкастинга

Чтобы NumPy мог успешно выполнить бродкастинг, массивы должны удовлетворять определённым условиям:

1. Если два массива имеют разное число осей (размерностей), к массиву с меньшим числом осей добавляются дополнительные оси слева (слева дополняется единичными измерениями).
2. Если размеры по одной из осей различны, то массив с размером 1 по этой оси «растягивается», чтобы соответствовать большему размеру.
3. Если размеры не совпадают и не равны 1, операция невозможна, и NumPy вызовет ошибку.

#### Примеры применения правил

##### Пример 1: одинаковые размеры

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # Размер (2, 3)
B = np.array([[10, 20, 30], [40, 50, 60]])  # Размер (2, 3)

# Операция возможна, так как размеры массивов совпадают
C = A + B
print(C)

[[11 22 33]
 [44 55 66]]


##### Пример 2: один из массивов с размером 1


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # Размер (2, 3)
B = np.array([[10], [20]])  # Размер (2, 1)

# Бродкастинг: массив B будет расширен до размера (2, 3)
# B станет [[10, 10, 10], [20, 20, 20]]
C = A + B
print(C)

[[11 12 13]
 [24 25 26]]


##### Пример 3: разные размерности

In [ ]:
A = np.array([1, 2, 3])  # Размер (3,)
B = np.array([[10], [20], [30]])  # Размер (3, 1)

# Бродкастинг расширяет A до (3, 3) и B до (3, 3):
# A станет [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
# B станет [[10, 10, 10], [20, 20, 20], [30, 30, 30]]
C = A + B
print(C)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


### 3. Почему бродкастинг полезен?

Бродкастинг позволяет работать с данными без необходимости явного копирования данных или создания дополнительных массивов. Это делает код более компактным, понятным и оптимизированным по памяти.

Рассмотрим два варианта выполнения одинаковой операции: с бродкастингом и без.

#### Без бродкастинга (явное создание дополнительных массивов)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([10])

# Без бродкастинга приходится расширять массив вручную
B_expanded = np.array([10, 10, 10])
C = A + B_expanded

В этом случае вам пришлось явно создать расширенную версию массива `B`, что требует дополнительной памяти и делает код менее элегантным.

#### С бродкастингом

In [ ]:
A = np.array([1, 2, 3])
B = np.array([10])

# С бродкастингом NumPy делает всё автоматически
C = A + B

С бродкастингом не нужно создавать промежуточные массивы, а операция выполняется быстрее и потребляет меньше памяти.

### 4. Как избежать ошибок при бродкастинге?

Хотя бродкастинг упрощает работу с массивами, нужно быть внимательным к размерностям массивов. Если размеры не удовлетворяют правилам бродкастинга, то NumPy выдаст ошибку.

#### Пример ошибки бродкастинга

In [ ]:
A = np.array([[1, 2], [3, 4]])  # Размер (2, 2)
B = np.array([10, 20, 30])  # Размер (3,)

# Здесь операция вызовет ошибку, так как размеры несовместимы
C = A + B  # ValueError: operands could not be broadcast together with shapes (2,2) (3,)

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

Для предотвращения ошибок нужно следовать правилам бродкастинга, описанным выше.

### 5. Применение бродкастинга

#### Скалярное умножение

Часто используемый пример бродкастинга — умножение массива на скаляр. Скаляр автоматически расширяется до размеров всего массива.

In [ ]:
A = np.array([1, 2, 3])
B = 10

# Бродкастинг скаляра
C = A * B
print(C)

[10 20 30]



#### Применение по строкам или столбцам

Часто нужно выполнять операции с массивом вдоль одной из осей. Например, если у вас есть матрица данных, и вы хотите вычесть из каждой строки вектор средних значений.

In [ ]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Размер (3, 3)
mean = np.array([4, 5, 6])  # Средние значения по столбцам (размер (3,))

# Вычитание средних значений из каждой строки
result = data - mean
print(result)

[[-3 -3 -3]
 [ 0  0  0]
 [ 3  3  3]]


### 6. Продвинутые примеры бродкастинга

#### Добавление нового измерения

Иногда нужно явно добавить ось в массив для выполнения бродкастинга. Это можно сделать с помощью метода `np.newaxis`.

In [ ]:
A = np.array([1, 2, 3])  # Размер (3,)
B = np.array([10, 20, 30])  # Размер (3,)

# Добавим новое измерение
A_reshaped = A[:, np.newaxis]  # Размер станет (3, 1)

# Теперь возможен бродкастинг
C = A_reshaped + B  # Размер (3, 3)
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


#### Бродкастинг и математические функции

Бродкастинг

 работает с большинством функций из библиотеки `NumPy`, таких как `sin`, `cos`, `exp` и другие.

In [ ]:
x = np.linspace(0, np.pi, 3)  # Массив [0, pi/2, pi]
y = np.array([[1], [2], [3]])  # Размер (3, 1)

# Бродкастинг и применение синуса
result = np.sin(x) * y
print(result)

[[0.0000000e+00 1.0000000e+00 1.2246468e-16]
 [0.0000000e+00 2.0000000e+00 2.4492936e-16]
 [0.0000000e+00 3.0000000e+00 3.6739404e-16]]


# Фильтрация массивов в Numpy

Фильтрация в Numpy осуществляется с помощью булевых массивов. Булевый массив — это массив, содержащий значения `True` или `False`, которые определяют, удовлетворяет ли каждый элемент исходного массива заданному условию.

### Булевый массив

Создание булевого массива начинается с определения условия, которое будет применяться ко всем элементам массива. Например, если у нас есть массив, содержащий числа, мы можем создать булевый массив, который будет указывать, какие из этих чисел больше заданного значения. Рассмотрим это на примере:

In [ ]:
import numpy as np

A = np.array([1, 2, 3, 4, 5])  # Исходный массив
B = A > 3  # Создаем булевый массив, который указывает, какие элементы больше 3
print(B)

[False False False  True  True]


В этом примере массив `B` содержит `True` для тех элементов массива `A`, которые больше 3, и `False` для остальных. Это позволяет нам легко фильтровать массив в дальнейшем.

## Фильтрация массивов

Фильтрация массива происходит с использованием булевого массива как индекса. Это позволяет извлекать только те элементы, которые удовлетворяют заданному условию.

### Пример фильтрации

Рассмотрим, как мы можем использовать булевый массив, чтобы извлечь элементы, которые больше 3 из массива `A`:

In [ ]:
filtered_A = A[B]  # Используем булевый массив для фильтрации
print(filtered_A)

[4 5]


В данном случае `filtered_A` содержит только те элементы из `A`, для которых в `B` стояло `True`.

## Условия фильтрации

Теперь давайте рассмотрим, как мы можем использовать различные условия для фильтрации массивов. Мы можем фильтровать массивы по четности, диапазону значений и другим критериям.

### Фильтрация по четности

Предположим, что мы хотим извлечь все четные числа из массива. Мы можем создать булевый массив, проверяющий, делится ли каждый элемент на 2:


In [ ]:
A = np.array([1, 2, 3, 4, 5, 6])  # Исходный массив
even_mask = A % 2 == 0  # Создаем булевый массив для четных чисел
filtered_even = A[even_mask]  # Фильтруем массив
print(filtered_even)

[2 4 6]


Здесь `even_mask` содержит `True` для всех четных чисел, что позволяет нам легко извлечь их из массива `A`.

### Фильтрация по диапазону

Теперь давайте рассмотрим фильтрацию по диапазону значений. Предположим, что мы хотим получить все элементы массива, которые находятся в диапазоне от 20 до 40:


In [ ]:
A = np.array([10, 20, 30, 40, 50])  # Исходный массив
range_mask = (A >= 20) & (A <= 40)  # Создаем булевый массив для диапазона
filtered_range = A[range_mask]  # Фильтруем массив
print(filtered_range)

[20 30 40]


Здесь мы используем логическое "И" (`&`), чтобы объединить два условия: больше или равно 20 и меньше или равно 40.

### Многоуровневая фильтрация

Мы можем комбинировать условия для более сложной фильтрации. Например, давайте извлечем все четные числа, которые больше 5:


In [ ]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # Исходный массив
complex_mask = (A % 2 == 0) & (A > 5)  # Создаем сложный булевый массив
filtered_complex = A[complex_mask]  # Фильтруем массив
print(filtered_complex)

[ 6  8 10]


В данном примере мы сначала проверяем, является ли число четным, а затем — больше ли оно 5, объединяя оба условия.

### Фильтрация с использованием функций

Иногда бывает полезно использовать функции для определения условий. Например, мы можем отфильтровать числа на основе того, являются ли они квадратами целых чисел:

In [ ]:
def is_square(n):
    return (n ** 0.5).is_integer()  # Проверяем, является ли число квадратом

A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # Исходный массив
square_mask = np.vectorize(is_square)(A)  # Применяем функцию ко всем элементам
filtered_squares = A[square_mask]  # Фильтруем массив
print(filtered_squares)

[1 4 9]


Здесь мы используем `np.vectorize`, чтобы применить функцию `is_square` ко всем элементам массива `A`.

## Использование функций `numpy.where`, `numpy.extract` и `numpy.nonzero`

Теперь давайте рассмотрим несколько дополнительных функций, которые помогают в фильтрации массивов.

### Функция `numpy.where`

`numpy.where` позволяет находить индексы элементов, удовлетворяющих определенному условию. Она также может использоваться для замены значений в массиве.

#### Пример нахождения индексов

Рассмотрим пример, в котором мы хотим найти индексы элементов массива, которые больше 30:

In [ ]:
A = np.array([10, 20, 30, 40, 50])  # Исходный массив
indices = np.where(A > 30)  # Находим индексы элементов больше 30
print(indices)

(array([3, 4]),)


Здесь `np.where` возвращает индексы элементов, которые соответствуют условию.

#### Замена значений

Функцию `np.where` также можно использовать для замены значений. Например, заменим все числа меньше 30 на 0:

In [ ]:
B = np.where(A < 30, 0, A)  # Заменяем числа меньше 30 на 0
print(B)

[ 0  0 30 40 50]


В этом случае `np.where` возвращает массив, в котором элементы меньше 30 заменены на 0, а остальные остаются без изменений.

### Функция `numpy.extract`

`numpy.extract` позволяет извлекать элементы массива на основе булевого условия.

#### Пример использования

Давайте создадим массив и извлечем из него элементы, которые больше 3:

In [ ]:
A = np.array([1, 2, 3, 4, 5])  # Исходный массив
condition = A > 3  # Создаем булевый массив
filtered = np.extract(condition, A)  # Извлекаем элементы
print(filtered)

[4 5]


Здесь `np.extract` позволяет получить только те элементы массива, которые удовлетворяют условию.

### Функция `numpy.nonzero`

`numpy.nonzero` возвращает индексы ненулевых элементов массива. Это полезно, если вам нужно получить индексы элементов, удовлетворяющих определенному условию.

#### Пример использования

In [ ]:
A = np.array([0, 1, 0, 3, 0, 5])  # Исходный массив
indices = np.nonzero(A)  # Находим индексы ненулевых элементов
print(indices)

(array([1, 3, 5]),)


Здесь `np.nonzero` возвращает индексы элементов массива, которые не равны нулю.


## Функция `numpy.unique`

Функция `numpy.unique` используется для получения уникальных значений из массива. Она возвращает массив уникальных значений и может также возвращать индексы и счетчики этих значений. Это особенно полезно, если вы хотите узнать, какие уникальные элементы присутствуют в данных, а также их количество.

### Синтаксис
```python
numpy.unique(arr, return_index=False, return_inverse=False, return_counts=False)
```

- `arr`: входной массив.
- `return_index`: если `True`, возвращает индексы первого вхождения уникальных значений.
- `return_inverse`: если `True`, возвращает индексы для восстановления исходного массива из уникальных значений.
- `return_counts`: если `True`, возвращает количество вхождений каждого уникального значения.

### Пример использования

Рассмотрим, как использовать `numpy.unique` для извлечения уникальных элементов из массива:



In [ ]:
import numpy as np

A = np.array([1, 2, 2, 3, 4, 4, 4, 5])  # Исходный массив
unique_values = np.unique(A)  # Находим уникальные значения
print(unique_values)

[1 2 3 4 5]


В этом примере функция `np.unique` возвращает массив, содержащий только уникальные элементы из `A`.

### Получение индексов уникальных значений

Если вам нужно знать индексы, по которым появляются уникальные значения, вы можете использовать параметр `return_index`:

In [ ]:
unique_values, indices = np.unique(A, return_index=True)
print(unique_values)
print(indices)

[1 2 3 4 5]
[0 1 3 4 7]


Здесь `indices` содержит индексы первого вхождения каждого уникального элемента в исходном массиве.

### Подсчет вхождений уникальных значений

Если вас интересует, сколько раз каждое уникальное значение встречается в массиве, используйте параметр `return_counts`:

In [ ]:
unique_values, counts = np.unique(A, return_counts=True)
print(unique_values)
print(counts)

[1 2 3 4 5]
[1 2 1 3 1]


Здесь `counts` показывает, сколько раз каждое уникальное значение появляется в массиве `A`.

### Применение в фильтрации

Функцию `np.unique` также можно использовать для фильтрации. Например, если вы хотите получить только уникальные четные числа из массива:

In [ ]:
A = np.array([1, 2, 2, 4, 4, 6, 7, 8])  # Исходный массив
even_numbers = A[A % 2 == 0]  # Извлекаем четные числа
unique_even_numbers = np.unique(even_numbers)  # Находим уникальные четные числа
print(unique_even_numbers)

[2 4 6 8]


## Линейная алгебра

Модуль `numpy.linalg` в библиотеке `NumPy` предоставляет мощные инструменты для выполнения операций линейной алгебры. Он позволяет выполнять такие задачи, как умножение матриц, вычисление обратных матриц, нахождение собственных значений и векторов, определителей, а также решение систем линейных уравнений. Линейная алгебра является фундаментальной областью математики, на которой базируются многие области вычислительных наук, включая машинное обучение, обработку сигналов и компьютерную графику.

### Пример: Умножение матриц

Умножение матриц — это основная операция линейной алгебры. Если $A$ — это матрица размером $m \times n$, а $B$ — матрица размером $n \times p$, то результатом их умножения $C = A \times B$ будет матрица размером $m \times p$, где каждый элемент $C_{ij}$ рассчитывается как:

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
$$

Рассмотрим пример умножения двух матриц с помощью NumPy:


In [ ]:
import numpy as np

# Создание двух матриц
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Умножение матриц
product = np.dot(matrix_a, matrix_b)
print(product)

[[19 22]
 [43 50]]


### Обратная матрица

Обратная матрица $A^{-1}$ существует только для квадратных матриц с ненулевым определителем. Если матрица $A$ обратима, то выполняется следующее свойство:

$$
A \times A^{-1} = A^{-1} \times A = I
$$

где $I$ — единичная матрица. Для нахождения обратной матрицы используется функция `numpy.linalg.inv()`.

In [ ]:
# Находить обратную матрицу
inverse_matrix = np.linalg.inv(matrix_a)
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


### Определитель матрицы

Определитель квадратной матрицы $A$ является числом, которое даёт информацию о свойствах матрицы, таких как возможность существования обратной матрицы. Для матрицы $A$ размером $n \times n$ определитель обозначается как $\text{det}(A)$ и вычисляется по рекурсивной формуле для больших матриц. Если определитель $\text{det}(A) = 0$, то матрица вырождена и не имеет обратной.

Пример вычисления определителя:

$$
\text{det}(A) = ad - bc
$$

для матрицы $A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$.

In [ ]:
# Вычисление определителя матрицы
det_matrix = np.linalg.det(matrix_a)
print(det_matrix)

-2.0000000000000004



### Собственные значения и собственные векторы

Собственные значения и собственные векторы играют важную роль в диагонализации матриц и во многих задачах, таких как PCA (Principal Component Analysis). Для квадратной матрицы $A$, собственное значение $\lambda$ и собственный вектор $v$ удовлетворяют уравнению:

$$
A v = \lambda v
$$

Функция `numpy.linalg.eig()` позволяет вычислить собственные значения и собственные векторы:

In [ ]:
# Нахождение собственных значений и векторов
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
print("Собственные значения:", eigenvalues)
print("Собственные векторы:\n", eigenvectors)

Собственные значения: [-0.37228132  5.37228132]
Собственные векторы:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Решение систем линейных уравнений

Системы линейных уравнений вида $Ax = b$, где $A$ — матрица коэффициентов, а $b$ — вектор значений, могут быть решены с помощью метода Гаусса или через нахождение обратной матрицы. В NumPy есть функция `numpy.linalg.solve()`, которая решает такие системы без необходимости вычисления обратной матрицы напрямую:


In [ ]:
# Решение системы уравнений Ax = b
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

x = np.linalg.solve(A, b)
print(x)

[2. 3.]


### Транспонирование матриц

Транспонирование матрицы $A$, обозначаемое как $A^T$, заключается в замене строк матрицы на её столбцы. Для матрицы $A$ транспонированная матрица $A^T$ будет иметь элементы $A_{ij}$ в позиции $A_{ji}$. В NumPy для транспонирования используется атрибут `.T`.

### Норма матрицы или вектора

Норма матрицы или вектора — это мера "длины" или "размера". Для векторов наиболее часто используется евклидова норма:

$$
||v|| = \sqrt{v_1^2 + v_2^2 + \dots + v_n^2}
$$

Для матриц можно использовать различные нормы, такие как фробениусова норма:

$$
||A||_F = \sqrt{\sum_{i,j} A_{ij}^2}
$$

Пример вычисления нормы вектора с помощью `numpy.linalg.norm()`:

In [ ]:
# Вычисление нормы вектора
vector = np.array([1, 2, 3])
norm = np.linalg.norm(vector)
print(norm)

3.7416573867739413


### Сингулярное разложение (SVD)

Сингулярное разложение (SVD) — это факторизация матрицы в произведение трёх матриц:

$$
A = U \Sigma V^T
$$

где $U$ и $V$ — ортогональные матрицы, а $\Sigma$ — диагональная матрица с сингулярными числами. SVD используется в задачах, таких как уменьшение размерности и сжатие данных.

In [ ]:
# Сингулярное разложение матрицы
U, S, Vt = np.linalg.svd(matrix_a)
print("U:\n", U)
print("S:", S)
print("V^T:\n", Vt)

U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S: [5.4649857  0.36596619]
V^T:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]



### Нахождение ранга матрицы

Ранг матрицы — это максимальное число линейно независимых строк или столбцов матрицы. Ранг показывает, насколько "сильно" или "полно" матрица содержит информацию. Если ранг матрицы меньше её максимального возможного значения (для квадратной матрицы это её размер), то матрица является вырожденной (необратимой).

В NumPy для вычисления ранга используется функция `numpy.linalg.matrix_rank()`:


In [ ]:
# Нахождение ранга матрицы
rank_matrix = np.linalg.matrix_rank(matrix_a)
print(rank_matrix)

2


### Кратчайшее расстояние (скалярное произведение векторов)

Скалярное произведение двух векторов $\mathbf{a} \cdot \mathbf{b}$ вычисляется как:

$$
\mathbf{a} \cdot \mathbf{b} = a_1b_1 + a_2b_2 + \dots + a_nb_n
$$

Если результат равен нулю, то векторы ортогональны. Это используется для нахождения углов между векторами, анализа корреляции и решения задач в физике и машинном обучении.

In [ ]:
# Скалярное произведение векторов
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

dot_product = np.dot(vector_a, vector_b)
print(dot_product)

32


### Векторное произведение (только для 3-мерных векторов)

Векторное произведение двух векторов $\mathbf{a}$ и $\mathbf{b}$ определено только для 3-мерных векторов и возвращает новый вектор, перпендикулярный к обоим исходным в пространстве:

$$
\mathbf{a} \times \mathbf{b} = \mathbf{c}
$$

Формула для векторного произведения в 3D:

$$
\mathbf{c} = (a_2b_3 - a_3b_2, a_3b_1 - a_1b_3, a_1b_2 - a_2b_1)
$$

Для нахождения векторного произведения в NumPy используется функция `numpy.cross()`:

In [ ]:
# Векторное произведение
cross_product = np.cross(vector_a, vector_b)
print(cross_product)

[-3  6 -3]



### QR-разложение

QR-разложение — это разложение матрицы $A$ на произведение ортогональной матрицы $Q$ и верхнетреугольной матрицы $R$:

$$
A = QR
$$

QR-разложение используется в различных численных методах, например, для решения систем линейных уравнений и нахождения собственных значений.


In [ ]:
# QR-разложение
Q, R = np.linalg.qr(matrix_a)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


### Решение переопределенных систем уравнений (метод наименьших квадратов)

В случае, когда система уравнений переопределена (больше уравнений, чем переменных), применяется метод наименьших квадратов. В NumPy это можно сделать с помощью функции `numpy.linalg.lstsq()`, которая находит приближённое решение:

$$
Ax \approx b
$$

In [ ]:
# Решение системы уравнений методом наименьших квадратов
A = np.array([[1, 1], [1, 2], [1, 3]])
b = np.array([1, 2, 2])

x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
print("Решение:", x)

Решение: [0.66666667 0.5       ]


### Характеристический многочлен матрицы

Характеристический многочлен $p(\lambda)$ матрицы $A$ помогает найти её собственные значения. Этот многочлен определяется как:

$$
p(\lambda) = \text{det}(A - \lambda I)
$$

где $I$ — единичная матрица, а $\lambda$ — переменная. С помощью характеристического многочлена можно анализировать спектр матрицы.

В NumPy нахождение собственных значений можно сделать через `numpy.linalg.eigvals()`.


In [ ]:
# Нахождение собственных значений
eigenvalues = np.linalg.eigvals(matrix_a)
print("Собственные значения:", eigenvalues)

Собственные значения: [-0.37228132  5.37228132]


### Ортогонализация Грама-Шмидта

Ортогонализация Грама-Шмидта — это метод, который позволяет преобразовать набор векторов в ортогональный набор. Этот процесс часто используется в численных методах для решения систем уравнений и в других задачах линейной алгебры.

### Матричные нормы

Норма матрицы — это мера её "размера". В дополнение к фробениусовой норме $||A||_F$, существуют и другие виды норм, такие как 1-норма (максимальная сумма элементов столбцов) и бесконечная норма (максимальная сумма элементов строк):

$$
||A||_1 = \max_j \sum_i |a_{ij}|
$$
$$
||A||_\infty = \max_i \sum_j |a_{ij}|
$$


In [ ]:
# 1-норма и бесконечная норма
norm_1 = np.linalg.norm(matrix_a, 1)
norm_inf = np.linalg.norm(matrix_a, np.inf)

print("1-норма:", norm_1)
print("Бесконечная норма:", norm_inf)

1-норма: 6.0
Бесконечная норма: 7.0


### Матричная псевдообратная (псевдоинверсия)

Псевдообратная матрица (псевдоинверсия) — это обобщение обратной матрицы для неквадратных или вырожденных матриц. Она используется для решения систем линейных уравнений, где точное решение не может быть найдено. В NumPy для этого используется функция `numpy.linalg.pinv()`:

In [ ]:
# Нахождение псевдообратной матрицы
pseudo_inverse = np.linalg.pinv(matrix_a)
print(pseudo_inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


Таким образом, модуль `numpy.linalg` предоставляет широкий набор функций для работы с линейной алгеброй, который охватывает все основные и продвинутые задачи, включая работу с матрицами, векторами и системами уравнений. Множество этих методов и операций является основой для сложных вычислений в таких областях, как машинное обучение, анализ данных и численные методы.


## Вопросы для самопроверки

1. Что такое NumPy и для чего он используется?
2. Как установить библиотеку NumPy?
3. Что такое объект `ndarray` в NumPy?
4. Как создать одномерный массив с помощью NumPy?
5. Приведите пример создания двумерного массива.
6. Как создать трехмерный массив в NumPy?
7. Какие свойства массивов можно получить с помощью `shape` и `dtype`?
8. Как создать массив, заполненный нулями?
9. Как создать массив, заполненный единицами?
10. Как создать массив с случайными числами от 0 до 1?
11. Как осуществляется индексация в одномерных массивах?
12. Как получить доступ к элементу двумерного массива по его индексам?
13. Что такое булева индексация и как она работает?
14. Приведите пример использования булевой индексации.
15. Как можно извлечь подмассив из двумерного массива с помощью срезов?
16. Как работает срез в одномерных массивах?
17. Что такое обычная индексация в NumPy?
18. Как использовать индексацию массивом индексов (Fancy indexing)?
19. Как работает индексация с помощью `np.ix_`?
20. Что делает оператор `...` в NumPy?
21. Как добавить новую ось в массив с помощью `np.newaxis`?
22. Как выполняются математические операции над массивами в NumPy?
23. Как сложить два массива в NumPy?
24. Что такое универсальные функции (ufuncs) в NumPy?
25. Как вычислить сумму всех элементов массива?
26. Как найти среднее значение массива с помощью NumPy?
27. Как транспонировать массив в NumPy?
28. Как изменить форму массива с помощью `reshape`?
29. Как объединить два массива в NumPy?
30. Как разделить массив на несколько частей?
31. Что такое бродкастинг в NumPy?
32. Как работают правила бродкастинга?
33. Приведите пример бродкастинга с массивами разной размерности.
34. Как найти обратную матрицу в NumPy?
35. Что такое определитель матрицы и как его вычислить?
36. Как найти собственные значения и собственные векторы матрицы?
37. Как решить систему линейных уравнений с помощью NumPy?
38. Как вычислить норму вектора в NumPy?
39. Что такое сингулярное разложение (SVD)?
40. Как использовать функцию `numpy.linalg.solve()`?
41. Какие операции можно выполнять с матрицами в модуле `numpy.linalg`?
42. Как вычислить фробениусову норму матрицы?
43. Как создать массив с заданными значениями, используя `np.arange()`?
44. Как получить максимальное и минимальное значение в массиве?
45. Как применить функцию к каждому элементу массива?
46. Как использовать `np.linspace()` для создания массива?
47. Как извлечь диагональные элементы матрицы?
48. Как использовать `np.concatenate()` для объединения массивов?
49. Как использовать `np.split()` для разделения массива?
50. Как можно использовать NumPy для обработки данных в машинном обучении?

### Фильтрация

1. Что такое булевый массив в Numpy и как его создать?
2. Как с помощью булевого массива фильтровать данные в массиве?
3. Как создать булевый массив, который проверяет, какие элементы массива больше заданного значения?
4. Как с помощью булевых массивов отфильтровать все четные числа в массиве?
5. Как создать булевый массив для фильтрации элементов, находящихся в определенном диапазоне значений?
6. Что произойдет, если использовать булевый массив для индексации исходного массива?
7. Как объединять несколько условий для фильтрации (например, проверка на четность и на диапазон)?
8. Как использовать функцию `numpy.where` для нахождения индексов элементов, соответствующих определенному условию?
9. Как заменить значения в массиве на основе условия с использованием функции `numpy.where`?
10. Для чего используется функция `numpy.extract` и чем она отличается от фильтрации с использованием булевых массивов?
11. Как использовать функцию `numpy.nonzero` и в чем ее назначение?
12. Как с помощью функции `numpy.unique` получить только уникальные элементы массива?
13. Что возвращает функция `numpy.unique`, если использовать параметры `return_index` и `return_counts`?
14. Как извлечь уникальные четные числа из массива, используя функции Numpy?
15. В чем разница между фильтрацией с использованием булевых массивов и функциями `numpy.extract` и `numpy.where`?



###Линейная алгебра

1. **Что такое определитель квадратной матрицы? Какую информацию он несёт?**
2. **Как вычисляется определитель для матрицы 2×2? Приведите пример.**
3. **Какие свойства матрицы определяются через её определитель? Что означает, если определитель равен нулю?**
4. **Как найти собственные значения и собственные векторы матрицы? Приведите формулу и объясните её.**
5. **Чем различаются ортогональные матрицы $U$ и $V$ в сингулярном разложении матрицы? Что такое сингулярные числа?**
6. **Какие задачи решаются с помощью сингулярного разложения (SVD)? Приведите пример.**
7. **Какой смысл имеет ранг матрицы? Как его вычислить?**
8. **В каких случаях используется метод наименьших квадратов для решения системы линейных уравнений?**
9. **Что такое транспонирование матрицы? Как найти транспонированную матрицу?**
10. **Что представляет собой характеристический многочлен матрицы и как он связан с собственными значениями?**
11. **Как можно решить систему линейных уравнений $Ax = b$ с помощью функции `numpy.linalg.solve()`? Приведите пример.**
12. **Что такое норма матрицы или вектора? Приведите пример вычисления евклидовой нормы вектора.**
13. **Как вычисляется векторное произведение для 3-мерных векторов? В чем его физический смысл?**
14. **Что означает QR-разложение матрицы? Как его можно применить для решения систем линейных уравнений?**
15. **Чем отличается псевдообратная матрица от обычной обратной матрицы? Когда она используется и как её вычислить?**



## Задачи для самостоятельной работы

## Основы numpy

1. Создайте одномерный массив из целых чисел от 1 до 10.
2. Создайте двумерный массив 3x3, заполненный нулями.
3. Создайте трехмерный массив 2x2x2 с элементами от 1 до 8.
4. Получите форму и тип данных массива, созданного в задаче 1.
5. Создайте массив единиц размером 4x4.
6. Создайте массив случайных чисел размером 3x2.
7. Извлеките элемент из второго столбца первой строки двумерного массива.
8. Используя булеву индексацию, отберите элементы массива, которые больше 5.
9. Создайте двумерный массив и извлеките первую строку.
10. Используйте срезы для получения последних двух элементов одномерного массива.
11. Создайте массив с элементами от 0 до 9 и извлеките каждый второй элемент.
12. Создайте массив 5x5 и получите подмассив, состоящий из элементов с 2 по 4 строки и 1 по 3 столбцы.
13. Используя `np.ix_`, получите подмассив из двумерного массива.
14. Примените поэлементное сложение к двум массивам одинакового размера.
15. Выполните поэлементное умножение двух массивов.
16. Используйте универсальную функцию для вычисления квадратного корня из одномерного массива.
17. Найдите среднее значение элементов массива.
18. Найдите минимальное и максимальное значение массива.
19. Транспонируйте двумерный массив.
20. Измените форму одномерного массива на двумерный.
21. Объедините два двумерных массива по строкам.
22. Разделите массив на 3 части.
23. Используйте отрицательные индексы для извлечения последнего элемента массива.
24. Извлеките диагональные элементы из двумерного массива.
25. Создайте булев массив, где значения `True` соответствуют элементам, большим 3.
26. Измените размерность массива, добавив новую ось.
27. Используйте комбинацию срезов и индексации для получения подмассива.
28. Создайте массив и получите сумму всех его элементов.
29. Выполните поэлементное деление двух массивов.
30. Сгенерируйте массив случайных чисел и найдите медиану.

### Broadcasting:

1. Создайте два массива размером (3, 3) и (1, 3). Примените Broadcasting для сложения этих двух массивов.
2. Имея массив размером (3, 3) и массив одномерный (3,), умножьте их с использованием Broadcasting.
3. Создайте массив размером (3, 3) и добавьте к нему число (скаляр). Примените Broadcasting для выполнения этой операции.
4. Используя Broadcasting, умножьте массив размером (4, 3) на массив размером (3,).
5. Попробуйте применить Broadcasting для сложения двух массивов разных форм, например, (2, 3) и (2, 1).
6. Создайте массив размером (5, 1) и массив одномерный (5,). Умножьте их с использованием Broadcasting.
7. Используя Broadcasting, сложите массив размером (3, 3) с массивом размером (3, 1).
8. Попробуйте применить Broadcasting для умножения массива размером (2, 3) на массив размером (2, 1).
9. Создайте массив размером (3, 3) и добавьте к нему одномерный массив (3,). Примените Broadcasting для выполнения этой операции.
10. Имея массив размером (3, 3) и массив одномерный (1, 3), умножьте их с использованием Broadcasting.
11. Используя Broadcasting, умножьте массив размером (4, 3) на массив размером (4, 1).
12. Создайте массив размером (3, 1) и массив одномерный (3,). Умножьте их с использованием Broadcasting.
13. Попробуйте применить Broadcasting для сложения двух массивов разных форм, например, (3, 2) и (1, 2).
14. Используя Broadcasting, сложите массив размером (3, 3) с массивом размером (1, 3).
15. Создайте массив размером (2, 3) и добавьте к нему одномерный массив (2,). Примените Broadcasting для выполнения этой операции.
16. Имея массив размером (3, 2) и массив одномерный (3,), умножьте их с использованием Broadcasting.
17. Используя Broadcasting, умножьте массив размером (3, 3) на массив размером (3, 1).
18. Создайте массив размером (2, 1) и массив одномерный (2,). Умножьте их с использованием Broadcasting.
19. Попробуйте применить Broadcasting для сложения двух массивов разных форм, например, (4, 2) и (4, 1).
20. Используя Broadcasting, сложите массив размером (2, 3) с массивом размером (2, 1).
21. Создайте массив размером (3, 4) и добавьте к нему скаляр. Примените Broadcasting для выполнения этой операции.
22. Имея массив размером (5, 2) и массив одномерный (5,), умножьте их с использованием Broadcasting.
23. Используя Broadcasting, сложите массив размером (2, 5) с массивом размером (1, 5).
24. Создайте массив размером (4, 3) и массив размером (4, 1). Умножьте их с использованием Broadcasting.
25. Попробуйте применить Broadcasting для сложения двух массивов разных форм, например, (3, 4) и (3, 1).
26. Используя Broadcasting, умножьте массив размером (6, 1) на массив размером (1, 4).
27. Создайте массив размером (2, 3) и добавьте к нему массив размером (2, 1). Примените Broadcasting для выполнения этой операции.
28. Имея массив размером (3, 3) и массив одномерный (1, 3), сложите их с использованием Broadcasting.
29. Используя Broadcasting, сложите массив размером (5, 2) с массивом размером (5, 1).
30. Попробуйте применить Broadcasting для умножения массива размером (3, 2) на массив размером (1, 2).


###Фильтрация


1. Создайте массив из чисел от 1 до 20. Используя булевый массив, отфильтруйте только числа, которые делятся на 3.
2. Напишите программу, которая создает массив из 10 случайных чисел и отфильтровывает те, что больше среднего значения массива.
3. Создайте массив с произвольными целыми числами от 0 до 100. Найдите и выведите все элементы, которые являются кратными 5.
4. Создайте булевый массив для фильтрации элементов из массива, которые меньше или равны 50.
5. Напишите программу, которая проверяет, какие элементы массива из 15 случайных чисел больше 30 и меньше 70, и выводит эти элементы.
6. Создайте массив с отрицательными и положительными числами. Отфильтруйте только положительные значения.
7. Напишите программу, которая создает массив и извлекает из него все элементы, являющиеся квадратами целых чисел.
8. Создайте массив из чисел от 1 до 100. Отфильтруйте все числа, кратные 7.
9. Создайте массив и выведите все его элементы, которые больше его медианы.
10. Сгенерируйте массив из 20 случайных чисел и отфильтруйте все значения, находящиеся в диапазоне от 10 до 50.
11. Создайте массив и отфильтруйте все элементы, у которых остаток от деления на 3 равен 1.
12. Используйте массив из случайных целых чисел и напишите программу, которая заменяет все отрицательные числа на 0 с использованием `numpy.where`.
13. Создайте массив и используйте функцию `numpy.where`, чтобы заменить все четные числа на их квадрат.
14. Сгенерируйте массив из чисел от 1 до 100 и найдите индексы элементов, которые делятся на 11.
15. Создайте массив с десятичными числами и используйте функцию `numpy.nonzero`, чтобы найти индексы ненулевых элементов.
16. Напишите программу, которая создает массив с произвольными числами и заменяет все числа больше 50 на 100 с помощью `numpy.where`.
17. Создайте массив из случайных чисел. Используя `numpy.extract`, получите все элементы, которые больше 30.
18. Создайте массив из случайных целых чисел от 1 до 100. Используя `numpy.nonzero`, найдите индексы всех элементов, равных нулю.
19. Напишите программу, которая фильтрует массив и извлекает из него только те элементы, которые являются простыми числами.
20. Создайте массив из 20 случайных чисел и отфильтруйте все числа, которые являются степенями двойки.
21. Создайте массив и используйте сложное условие для фильтрации всех чисел, которые больше 10 и одновременно четные.
22. Сгенерируйте массив случайных чисел от 1 до 50 и извлеките только нечетные числа, которые меньше 25.
23. Напишите программу, которая создает массив и отфильтровывает все элементы, которые делятся на 3, но не делятся на 5.
24. Используя массив случайных чисел, создайте булевый массив, который проверяет, какие числа больше среднего значения массива и одновременно кратны 4.
25. Создайте массив из 50 случайных чисел. Найдите и выведите уникальные элементы массива, которые являются четными числами.
26. Напишите программу, которая с помощью `numpy.where` заменяет все элементы массива, делящиеся на 5, на их квадраты.
27. Создайте массив случайных чисел и замените все отрицательные числа на их абсолютные значения с использованием `numpy.where`.
28. Сгенерируйте массив и отфильтруйте все элементы, которые являются нечетными и больше 50.
29. Создайте массив и отфильтруйте числа, которые являются квадратами целых чисел и одновременно четные.
30. Напишите программу, которая сгенерирует массив, заменит все числа, больше 70, на 100, а числа, меньше 30, — на 0 с использованием `numpy.where`.



###Линейная алгебра
1. Найдите определитель матрицы $A = \begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix}$.
2. Вычислите определитель матрицы $B = \begin{pmatrix} 1 & 2 & 3 \\ 0 & 1 & 4 \\ 5 & 6 & 0 \end{pmatrix}$.
3. Доказать, что если $\text{det}(A) = 0$, то матрица $A$ не имеет обратной.

4. Найдите собственные значения матрицы $C = \begin{pmatrix} 4 & 1 \\ 2 & 3 \end{pmatrix}$.
5. Найдите собственные векторы для собственных значений, найденных в задаче 4.
6. Для матрицы $D = \begin{pmatrix} 2 & 0 \\ 0 & -2 \end{pmatrix}$ найдите собственные значения и собственные векторы.
7. Решите систему уравнений:
   $$
   \begin{cases}
   2x + 3y = 5 \\
   4x - y = 1
   \end{cases}
   $$
8. Найдите решение системы уравнений:
   $$
   \begin{cases}
   x + 2y + 3z = 1 \\
   2x + 3y + z = 2 \\
   3x + y + 2z = 3
   \end{cases}
   $$
9. Решите систему уравнений методом наименьших квадратов:
   $$
   \begin{cases}
   x + y = 1 \\
   2x + 2y = 2 \\
   3x + 3y = 3
   \end{cases}
   $$
10. Найдите транспонированную матрицу для $E = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}$.
11. Найдите произведение матрицы $F = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$ и её транспонированной матрицы.
12. Вычислите евклидову норму вектора $v = \begin{pmatrix} 3 \\ 4 \end{pmatrix}$.
13. Найдите фробениусову норму матрицы $G = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$.
14. Вычислите 1-норму и бесконечную норму матрицы $H = \begin{pmatrix} 1 & -1 \\ 2 & 3 \end{pmatrix}$.
15. Выполните сингулярное разложение матрицы $I = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$.
16. Объясните, как можно использовать SVD для уменьшения размерности данных.
17. Найдите ранг матрицы $J = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix}$.
18. Доказать, что ранг матрицы не может превышать её меньший размер.

### Задачи на скалярное и векторное произведение
19. Вычислите скалярное произведение векторов $a = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$ и $b = \begin{pmatrix} 4 \\ 5 \\ 6 \end{pmatrix}$.
20. Найдите векторное произведение векторов $c = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$ и $d = \begin{pmatrix} 4 \\ 5 \\ 6 \end{pmatrix}$.
21. Выполните QR-разложение матрицы $K = \begin{pmatrix} 1 & 1 \\ 1 & 0 \\ 0 & 1 \end{pmatrix}$.
22. Объясните, как QR-разложение может быть использовано для решения систем уравнений.
23. Решите систему уравнений методом наименьших квадратов для данных:
   $$
   \begin{pmatrix}
   1 & 1 \\
   2 & 1 \\
   3 & 1
   \end{pmatrix}
   \begin{pmatrix}
   x \\
   y
   \end{pmatrix}
   =
   \begin{pmatrix}
   2 \\
   3 \\
   5
   \end{pmatrix}
   $$
24. Найдите характеристический многочлен матрицы $L = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$.
25. Определите собственные значения матрицы $M = \begin{pmatrix} 3 & 2 \\ 2 & 3 \end{pmatrix}$ с помощью характеристического многочлена.
26. Примените метод Грама-Шмидта к векторному набору $\{ \begin{pmatrix} 1 \\ 1 \end{pmatrix}, \begin{pmatrix} 1 \\ 0 \end{pmatrix} \}$.
27. Найдите псевдообратную матрицу для матрицы $N = \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix}$.
28. Объясните, как линейная алгебра используется в машинном обучении.
29. Приведите пример использования собственных значений в анализе данных.
30. Опишите, как QR-разложение может быть применено для численного решения уравнений.

31. Найти след квадратной матрицы (сумма элементов главной диагонали).
32. Найти собственные значения и собственные векторы квадратной матрицы.
33. Решить систему линейных уравнений, представив коэффициенты в виде матрицы.
34. Найти обратную матрицу для заданной квадратной матрицы.
35. Найти ранг матрицы.
36. Найти собственные значения квадратной матрицы.
37. Найти LU-разложение квадратной матрицы.
38. Найти QR-разложение матрицы.
39. Найти сингулярное разложение матрицы.
40. Найти оптимальное приближение для матрицы с помощью сингулярного разложения.
41. Найти собственные значения и собственные векторы для симметричной матрицы.
42. Найти собственные значения и собственные векторы для эрмитовой матрицы.
43. Найти псевдообратную матрицу.
44. Найти скалярное произведение векторов.
45. Найти векторное произведение векторов.
46. Найти смешанное произведение векторов.
47. Найти угол между двумя векторами.
48. Найти проекцию вектора на другой вектор.

### Дополнительные задачи
49. Найдите след матрицы $P = \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix}$.
50. Найдите собственные значения и собственные векторы матрицы $Q = \begin{pmatrix} 0 & 1 \\ -1 & 0 \end{pmatrix}$.
51. Решите систему линейных уравнений с использованием метода Гаусса:
   $$
   \begin{cases}
   x + 2y + 3z = 9 \\
   2x + 3y + z = 8 \\
   3x + y + 2z = 7
   \end{cases}
   $$
52. Найдите обратную матрицу для матрицы $R = \begin{pmatrix} 4 & 7 \\ 2 & 6 \end{pmatrix}$.
53. Найдите ранг матрицы $S = \begin{pmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 3 & 6 & 9 \end{pmatrix}$.
54. Найдите собственные значения матрицы $T = \begin{pmatrix} 5 & 4 \\ 2 & 1 \end{pmatrix}$.
55. Найдите LU-разложение матрицы $U = \begin{pmatrix} 2 & 3 \\ 5 & 4 \end{pmatrix}$.
56. Найдите QR-разложение матрицы $V = \begin{pmatrix} 1 & 1 \\ 1 & 0 \\ 0 & 1 \end{pmatrix}$.
57. Найдите сингулярное разложение матрицы $W = \begin{pmatrix} 1 & 0 \\ 0 & 1 \\ 1 & 1 \end{pmatrix}$.
58. Найдите оптимальное приближение для матрицы $X = \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix}$ с помощью сингулярного разложения.
59. Найдите собственные значения и собственные векторы для матрицы $Y = \begin{pmatrix} 2 & -1 \\ -1 & 2 \end{pmatrix}$.
60. Найдите угол между векторами $a = \begin{pmatrix} 1 \\ 2 \end{pmatrix}$ и $b = \begin{pmatrix} 3 \\ 4 \end{pmatrix}$.



##Задания примеры


Создайте массив единиц размером 4x4

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Сгенерируйте массив случайных чисел и найдите медиану

In [ ]:
b = np.array([1, 2, 2, 4, 1, 7, 9])
median_value = np.median(b)

print("Медиана:", median_value)

Медиана: 2.0


Создайте два массива размером (3, 3) и (1, 3). Примените Broadcasting для сложения этих двух массивов.

In [ ]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[10, 20, 30]])

result = array1 + array2

print("Первый массив:n", array1)
print("Второй массив:n", array2)
print("Результат сложения:n", result)

Первый массив:n [[1 2 3]
 [4 5 6]
 [7 8 9]]
Второй массив:n [[10 20 30]]
Результат сложения:n [[11 22 33]
 [14 25 36]
 [17 28 39]]


Создайте массив из чисел от 1 до 20. Используя булевый массив, отфильтруйте только числа, которые делятся на 3

In [ ]:
array = np.arange(1, 21)

boolean_mask = (array % 3 == 0)

filtered_array = array[boolean_mask]

print("Исходный массив:", array)
print("Числа, которые делятся на 3:", filtered_array)

Исходный массив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Числа, которые делятся на 3: [ 3  6  9 12 15 18]


Найдите определитель матрицы  $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$.


In [ ]:
a = np.array([[1, 2], [3, 4]])
det = np.linalg.det(a)
print(det)

-2.0000000000000004


##Задания для самостоятельных работ

1. Создайте двумерный массив и транспонируйте его
2. Создайте массив с произвольными целыми числами от 0 до 100. Найдите и выведите все элементы, которые являются кратными 5